### ISSUE TITLE
where is latest insane.py

### ISSUE THREAD

**Issue by YitaoGou** [Martini-Force-Field-Initiative/M3-Sterol-Parameters#1]
where I can download the latest insane.py script containing the new Martini 3 cholesterol model? I can only find the latest one in https://github.com/Tsjerk/MartiniTools/blob/master/insane.py

**Comment by Lp0lp** [comment]
My bad! It was not there. You can now find it in the main repository directory (or [here](https://github.com/Martini-Force-Field-Initiative/M3-Sterol-Parameters/blob/main/insane.py))! Enjoy.
